services:
  frontend:
    build:
      context: frontend
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - backend-frontend-net
    depends_on:
      - backend

  backend:
    build:
      context: backend
    env_file: ./backend/.env
    ports:
      - 8080:8080
    volumes:
      - ~/.m2:/root/.m2
    networks:
      - backend-db-net
      - backend-frontend-net
    depends_on:
      - db

  db:
    image: mysql:8
    env_file: ./db/.env
    networks:
      - backend-db-net
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306

networks:
  backend-frontend-net:
  backend-db-net:

volumes:
  db-data:
